print("Пожалуйста, введите данные сторон треугольника")
print("Сторона А, см")
a = float(input())
print("Сторона В, см")
b = float(input())
print("Сторона С, см")
c = float(input())
print("Периметр равен:")
print(float(a+b+c),"см")
print("Площадь равна:")
p = ((a+b+c)/2)
d=p*(p-a)*(p-b)*(p-c)
e = d ** (0.5)
# Квадратный корень
print(float(e), "кв.см")